### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Raj Sharma with analyatic service",
  "email": "kafka_test90@example.com",
  "address": "123 main street",
  "dateOfBirth": "2001-11-23",
  "registeredDate": "2024-11-28"
}

###